myMovieReviews/myMovieReviews/ReviewList/urls.py
from django.urls import path
from . import views

app_name = 'ReviewList'

urlpatterns = [
    path('', views.review_list, name='review_list'),  # 리뷰 리스트
    path('<int:id>/', views.review_detail, name='review_detail'),  # 리뷰 디테일
    path('new/', views.review_create, name='review_create'),  # 새 리뷰 작성
    path('<int:id>/edit/', views.review_update, name='review_update'),  # 리뷰 수정
    path('<int:id>/delete/', views.review_delete, name='review_delete'),  # 리뷰 삭제
]

myMovieReviews/myMovieReviews/myMovieReviews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ReviewList.urls')),  # 빈 경로를 reviews 앱으로 연결
]

myMovieReviews/myMovieReviews/ReviewList/models.py
from django.db import models

class Review(models.Model):
    title = models.TextField()  # 영화 제목
    release_year = models.IntegerField(null=True, blank=True) #개봉년도
    director = models.TextField()  # 감독
    main_actor = models.TextField()  # 주연
    genre = models.TextField()  # 장르
    rating = models.DecimalField(max_digits=3, decimal_places=1)  # 별점
    runtime = models.IntegerField()  # 러닝타임 분으로 표기
    content = models.TextField()  # 리뷰 내용
    created_at = models.DateTimeField(auto_now_add=True)  # 작성일

def __str__(self):
    return self.title

myMovieReviews/myMovieReviews/ReviewList/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from .models import Review

# 리뷰 리스트
def review_list(request):
    reviews = Review.objects.all()
    return render(request, 'review_list.html', {'reviews': reviews})

# 리뷰 디테일
def review_detail(request, id):
    review = get_object_or_404(Review, id=id)
    return render(request, 'review_detail.html', {'review': review})

# 리뷰 작성
def review_create(request):
    if request.method == 'POST':
        Review.objects.create(
            title=request.POST['title'],
            release_year=request.POST['release_year'],
            director=request.POST['director'],
            main_actor=request.POST['main_actor'],
            genre=request.POST['genre'],
            rating=request.POST['rating'],
            runtime=request.POST['runtime'],
            content=request.POST['content'],
        )
        return redirect('ReviewList:review_list')
    return render(request, 'review_form.html')

# 리뷰 수정
def review_update(request, id):
    review = get_object_or_404(Review, id=id)
    if request.method == 'POST':
        review.title = request.POST['title']
        review.release_year = request.POST['release_year']
        review.director = request.POST['director']
        review.main_actor = request.POST['main_actor']
        review.genre = request.POST['genre']
        review.rating = request.POST['rating']
        review.runtime = request.POST['runtime']
        review.content = request.POST['content']
        review.save()
        return redirect('ReviewList:review_detail', id=review.id)
    return render(request, 'review_form.html', {'review': review})

# 리뷰 삭제
def review_delete(request, id):
    review = get_object_or_404(Review, id=id)
    review.delete()
    return redirect('ReviewList:review_list')

myMovieReviews/myMovieReviews/ReviewList/templates/review_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ review.title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color:white;
        }

        header {
            background-color: #202020;
            color: white;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        header h1 {
            margin: 0;
            font-size: 24px;
        }

        header a {
            color: white;
            text-decoration: none;
            font-size: 16px;
            background-color: #ff5722;
            padding: 8px 12px;
            border-radius: 4px;
        }

        header a:hover {
            background-color: #e64a19;
        }
        .container {
            background-color: white;
            margin: 30px auto;
            padding: 20px;
            max-width: 800px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h2 {
            font-size: 28px;
            margin: 10px 0 20px;
            color: #333;
            text-align: center;
        }

        .main_review {
            background-color: #efefef;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .main_review p {
            margin: 10px 0;
            font-size: 16px;
            color: #555;
        }

        .main_review p strong {
            font-weight: bold;
            color: #333;
        }

        .review_content {
            font-size: 16px;
            line-height: 1.6;
            color: #444;
            margin-bottom: 20px;
        }

        .action_links {
            display: flex;
            justify-content: flex-end;
            gap: 10px;
        }

        .action_links a {
            text-decoration: none;
            color: white;
            background-color: #75a4d7;
            padding: 10px 15px;
            border-radius: 5px;
            font-size: 14px;
        }

        .action_links a:hover {
            background-color: #618ab6;
        }
    </style>
</head>
<body>
    <header>
        <h1>myMovieReviews🍿</h1>
        <a href="{% url 'ReviewList:review_create' %}">Add a new review</a>
    </header>

    <div class="container">
        <h2>{{ review.title }}</h2>
        <div class="main_review">
            <p><strong>개봉 연도:</strong> {{ review.release_year }}</p>
            <p><strong>감독:</strong> {{ review.director }}</p>
            <p><strong>주연:</strong> {{ review.main_actor }}</p>
            <p><strong>장르:</strong> {{ review.genre }}</p>
            <p><strong>별점:</strong> {{ review.rating }}</p>
            <p><strong>러닝타임:</strong> {{ review.runtime }}분</p>
        </div>
        <div class="review_content">
            <strong>리뷰 내용:</strong>
            <p>{{ review.content }}</p>
        </div>
        <div class="action_links">
            <a href="{% url 'ReviewList:review_list' %}">my Movie Reviews</a>
            <a href="{% url 'ReviewList:review_update' review.id %}">수정</a>
            <a href="{% url 'ReviewList:review_delete' review.id %}">삭제</a>
        </div>
    </div>
</body>
</html>

myMovieReviews/myMovieReviews/ReviewList/templates/review_form.html
<!DOCTYPE html>
<html>
<head>
    <title>리뷰 작성/수정</title>
    <style>
         body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color:white;
        }

        header {
            background-color: #202020;
            color: white;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        header h1 {
            margin: 0;
            font-size: 24px;
            color: white;
        }

        header a {
            color: white;
            text-decoration: none;
            font-size: 16px;
            background-color: #ff5722;
            padding: 8px 12px;
            border-radius: 4px;
        }

        header a:hover {
            background-color: #e64a19;
        }

        .container {
            background-color: white;
            margin: 30px auto;
            padding: 20px 30px;
            max-width: 600px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }
        form label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            color: #555;
        }

        form input[type="text"],
        form input[type="number"],
        form textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 14px;
        }

        form textarea {
            height: 100px;
            resize: none;
        }

        form button {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            background-color:#75a4d7;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        form button:hover {
            background-color:#618ab6;
        }
    </style>

    </style>
</head>
<body>
    <header>
        <h1>myMovieReviews🍿</h1>
        <a href="{% url 'ReviewList:review_create' %}">Add a new review</a>
    </header>

    <div class="container">
        <h1>MovieReviews🍿</h1>
        <form method="POST">
            {% csrf_token %}
            <label for="title">제목:</label>
            <input type="text" id="title" name="title" value="{{ review.title|default:'' }}">

            <label for="release_year">개봉년도:</label>
            <input type="number" id="release_year" name="release_year" value="{{ review.release_year|default:'' }}">

            <label for="genre">장르:</label>
            <input type="text" id="genre" name="genre" value="{{ review.genre|default:'' }}">

            <label for="rating">별점:</label>
            <input type="number" id="rating" step="0.1" name="rating" value="{{ review.rating|default:'' }}">

            <label for="runtime">러닝타임:</label>
            <input type="number" id="runtime" name="runtime" value="{{ review.runtime|default:'' }}">

            <label for="director">감독:</label>
            <input type="text" id="director" name="director" value="{{ review.director|default:'' }}">

            <label for="main_actor">주연배우:</label>
            <input type="text" id="main_actor" name="main_actor" value="{{ review.main_actor|default:'' }}">

            <label for="content">리뷰:</label>
            <textarea id="content" name="content">{{ review.content|default:'' }}</textarea>

            <button type="submit">Save</button>
        </form>
    </div>
</body>
</html>

myMovieReviews/myMovieReviews/ReviewList/templates/review_list.html
<!DOCTYPE html>
<html>
<head>
    <title>myMovieReviews</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color:white;
        }

        header {
            background-color: #202020;
            color: white;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        header h1 {
            margin: 0;
            font-size: 24px;
        }

        header a {
            color: white;
            text-decoration: none;
            font-size: 16px;
            background-color: #ff5722;
            padding: 8px 12px;
            border-radius: 4px;
        }

        header a:hover {
            background-color: #e64a19;
        }

        .container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            margin: 100px auto;
            max-width: 1200px;
        }

        .card {
            background: rgba(217, 213, 213, 0.292);
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            margin: 15px;
            padding: 15px;
            width: 250px;
            text-align: center;
            font-weight: bold;
        }

        .card h2 {
            font-size: 18px;
            margin: 40px 0;
        }

        .card a {
            text-decoration: none;
            font-weight: bold;
            color: black;
            text-align: left;
            font-size: 18px;
            margin: 20px;
        }

        .card p {
            margin: 5px 0;
            font-size: 14px;
            color: #555;
            text-align: left;
            
        }
    </style>
</head>
<body>
    <header>
        <h1>myMovieReviews🍿</h1>
        <a href="{% url 'ReviewList:review_create' %}">Add a new review</a>
    </header>

    <div class="container">
        {% for review in reviews %}
        <div class="card">
            <h2><a href="{% url 'ReviewList:review_detail' review.id %}">{{ review.title }}</a></h2>
            <p>개봉년도: {{ review.release_year }}</p>
            <p>장르: {{ review.genre }}</p>
            <p class="rating">별점: {{ review.rating }}점</p>
        </div>
        {% endfor %}
    </div>
</body>
</html>